version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - ${HOST}