"""avatar column

Revision ID: 3d5d90ae3651
Revises: e49dea0d774f
Create Date: 2025-07-31 08:41:49.178680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3d5d90ae3651"
down_revision: Union[str, Sequence[str], None] = "e49dea0d774f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "avatar",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "avatar",
        existing_type=sa.String(),
        type_=postgresql.BYTEA(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
