"""column name changed

Revision ID: 5c16531080e1
Revises: bd2c2ed302d8
Create Date: 2025-07-22 13:30:06.323492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c16531080e1"
down_revision: Union[str, Sequence[str], None] = "bd2c2ed302d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("oauth_id", sa.String(length=255), nullable=True))
    op.drop_index(op.f("ix_users_oauth_sub"), table_name="users")
    op.create_index(op.f("ix_users_oauth_id"), "users", ["oauth_id"], unique=True)
    op.drop_column("users", "oauth_sub")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "oauth_sub", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_users_oauth_id"), table_name="users")
    op.create_index(op.f("ix_users_oauth_sub"), "users", ["oauth_sub"], unique=True)
    op.drop_column("users", "oauth_id")
    # ### end Alembic commands ###
